[template]
src = "nginx-site.conf.tmpl"
dest = "/etc/nginx/default.d/default"
keys = [
  "/dockermicroservicedemo_app",
]
#check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
check_cmd = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "/usr/sbin/nginx -s reload"
