version: '2'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: --storageEngine wiredTiger
    volumes:
      # This would exist on MacOSX Host - permissions errors
      #- /Users/mitch/git/docker-microservice-demo/mongo/data:/data/db
      # Map this to boot2docker host FileSystem to keep mongo data between
      # container restarts
      - /data/db:/data/db
    depends_on:
      - grandcentral
  data:
    build: data/
    ports:
      - "5000:5000"
    volumes:
      - /Users/mitch/git/docker-microservice-demo/data/:/code/
    depends_on:
      - mongo
  app:
    build: app/
    ports:
      - "8000:8000"
    volumes:
      - /Users/mitch/git/docker-microservice-demo/app/:/code/
    depends_on:
      - data
#  web:
#    image/build:
#    ports:
#      - "80:80"
#    depends_on:
#      - app
  grandcentral:
    image: quay.io/coreos/etcd:v2.0.3
    ports:
      - "4001:4001"
      - "2380:2380"
      - "2379:2379"
    command: -initial-cluster-state new -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster-1
